# Generated by Django 3.0.5 on 2020-06-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='post_code',
        ),
    ]
