# Generated by Django 3.0.5 on 2020-10-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
