# Generated by Django 3.0.5 on 2020-10-21 09:32

import advertise.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='eng_name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.CharField(db_index=True, default=advertise.utils.generate_slug, editable=False, max_length=8, unique=True),
        ),
    ]
