# Generated by Django 3.0.5 on 2020-11-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='account_owner',
        ),
    ]
