# Generated by Django 3.0.5 on 2020-10-22 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201021_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_gift',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkdin_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter_id',
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('0', 'Linkdin'), ('1', 'Facebook'), ('2', 'Instagram'), ('3', 'Twitter')], max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='account.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
