# Generated by Django 3.0.5 on 2020-12-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201211_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='images/user.png', null=True, upload_to='images/profile_picture/%Y/%m'),
        ),
    ]
