# Generated by Django 3.0.5 on 2020-08-19 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200819_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentuser',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_give_comment', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='commentuser',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receive_comment', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='score',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='account.Profile'),
        ),
        migrations.AlterField(
            model_name='score',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_receiver', to='account.Profile'),
        ),
    ]
