# Generated by Django 3.0.5 on 2020-12-28 22:30

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201221_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentuser',
            name='slug',
            field=models.CharField(default=core.utils.generate_slug, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.CharField(default=core.utils.generate_slug, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='slug',
            field=models.CharField(default=core.utils.generate_slug, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='slug',
            field=models.CharField(default=core.utils.generate_slug, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.CharField(default=core.utils.generate_slug, editable=False, max_length=8, unique=True),
        ),
    ]
