# Generated by Django 3.0.5 on 2020-06-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200621_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follower_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following_count',
        ),
        migrations.AddField(
            model_name='user',
            name='follower_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
