# Generated by Django 3.0.5 on 2020-12-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201229_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='images/country'),
        ),
    ]
