# Generated by Django 3.0.5 on 2020-10-25 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201025_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_number',
            field=models.CharField(blank=True, max_length=24, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$'), django.core.validators.RegexValidator(regex='^.{24}$')]),
        ),
    ]
