# Generated by Django 3.0.5 on 2020-06-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200621_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('0', 'در انتظار'), ('1', 'تایید'), ('2', 'رد')], default=0, max_length=10),
        ),
    ]
