# Generated by Django 3.0.5 on 2020-08-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_last_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/country'),
        ),
    ]
