# Generated by Django 3.0.5 on 2020-06-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_follow_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_cart',
        ),
    ]
