# Generated by Django 3.0.5 on 2020-10-25 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201025_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_number',
            field=models.CharField(blank=True, max_length=24, null=True, validators=[django.core.validators.RegexValidator('^\\d{0,9}$'), django.core.validators.RegexValidator(message='Length has to be 4', regex='^.{5}$')]),
        ),
    ]
