# Generated by Django 3.0.5 on 2020-06-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200621_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='linkdin_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
