# Generated by Django 3.0.5 on 2020-10-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20201025_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/social'),
        ),
    ]
