# Generated by Django 3.0.5 on 2020-10-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_social_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='icon',
        ),
    ]
