# Generated by Django 3.0.5 on 2020-11-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionreceive',
            name='cardNumber',
            field=models.CharField(default='1', max_length=16),
            preserve_default=False,
        ),
    ]
