# Generated by Django 3.0.5 on 2020-09-06 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertise', '0011_auto_20200906_0626'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionReceive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transID', models.IntegerField()),
                ('amount', models.FloatField()),
                ('status', models.BooleanField()),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel', to='advertise.Packet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_packet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('status', models.BooleanField()),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel', to='advertise.Travel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_travel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='transaction',
        ),
    ]
