# Generated by Django 3.0.5 on 2020-11-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_transactionreceive_cardnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionreceive',
            name='paymentDate',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
