# Generated by Django 3.0.5 on 2020-12-28 22:30

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20201217_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='slug',
            field=models.CharField(default=core.utils.generate_slug, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionreceive',
            name='slug',
            field=models.CharField(default=core.utils.generate_slug, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionsend',
            name='slug',
            field=models.CharField(default=core.utils.generate_slug, editable=False, max_length=8, unique=True),
        ),
    ]
