# Generated by Django 3.0.5 on 2020-09-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200906_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionreceive',
            name='factorNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
