# Generated by Django 3.0.5 on 2020-11-21 09:53

import core.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_auto_20201121_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=24, null=True, validators=[django.core.validators.RegexValidator(message='شماره شبا نامعتبر است', regex='^\\d{1,24}$'), django.core.validators.RegexValidator(message='شماره شبا می\u200cبایست ۲۴ رقم باشد', regex='^.{24}$')])),
                ('slug', models.CharField(db_index=True, default=core.utils.generate_slug, editable=False, max_length=8, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
