# Generated by Django 3.0.5 on 2020-11-21 10:21

import core.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='transactionreceive',
            name='slug',
            field=models.CharField(db_index=True, default=core.utils.generate_slug, editable=False, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='transactionsend',
            name='bank',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='payment.Bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionsend',
            name='slug',
            field=models.CharField(db_index=True, default=core.utils.generate_slug, editable=False, max_length=8, unique=True),
        ),
    ]
