# Generated by Django 3.0.5 on 2020-11-21 10:24

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20201121_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsend',
            name='slug',
            field=models.CharField(db_index=True, default=core.utils.generate_slug, editable=False, max_length=8),
        ),
    ]
