# Generated by Django 3.0.5 on 2020-10-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200906_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsend',
            name='status',
            field=models.IntegerField(choices=[(0, 'در انتظار تایید'), (1, 'تایید پرداخت'), (2, 'انجام شده'), (3, 'انجام نشده')]),
        ),
    ]
