# Generated by Django 3.0.5 on 2020-10-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20201009_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsend',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='transactionsend',
            name='status',
            field=models.IntegerField(choices=[(0, 'در انتظار تایید'), (1, 'تایید پرداخت'), (2, 'انجام شده'), (3, 'انجام نشده')], default=0),
        ),
    ]
