# Generated by Django 3.0.5 on 2020-11-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20201121_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionreceive',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='transactionsend',
            name='slug',
        ),
    ]
