# Generated by Django 3.0.5 on 2020-10-11 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0045_auto_20201011_1628'),
        ('payment', '0007_auto_20201009_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionreceive',
            name='packet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel', to='advertise.Packet'),
        ),
        migrations.AlterField(
            model_name='transactionsend',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel', to='advertise.Travel'),
        ),
    ]
