# Generated by Django 3.0.5 on 2020-11-21 10:26

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20201121_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionreceive',
            name='slug',
            field=models.CharField(db_index=True, default=core.utils.generate_slug, editable=False, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='transactionsend',
            name='slug',
            field=models.CharField(db_index=True, default=core.utils.generate_slug, editable=False, max_length=8, unique=True),
        ),
    ]
