# Generated by Django 3.0.5 on 2020-12-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='not_seen',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
