# Generated by Django 3.0.5 on 2020-11-21 22:57

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='slug',
            field=models.CharField(db_index=True, default=core.utils.generate_slug, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
