# Generated by Django 3.0.5 on 2020-11-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201122_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
