# Generated by Django 3.0.5 on 2020-07-18 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20200714_1640'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='conversation',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='massage',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='massage', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
