# Generated by Django 3.0.5 on 2020-11-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201123_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='type_text',
            field=models.IntegerField(choices=[(0, 'p2p'), (1, 'admin')], default=0),
        ),
    ]
