# Generated by Django 3.0.5 on 2020-12-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201211_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
