# Generated by Django 3.0.5 on 2020-07-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200711_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatid',
            options={},
        ),
        migrations.AlterModelOptions(
            name='massage',
            options={},
        ),
        migrations.AlterField(
            model_name='chatid',
            name='chat_id',
            field=models.CharField(default='523674', editable=False, max_length=8, unique=True),
        ),
    ]
