# Generated by Django 3.0.5 on 2020-11-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_massage_type_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='offer',
        ),
    ]
