# Generated by Django 3.0.5 on 2020-07-22 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0003_auto_20200722_1431'),
        ('chat', '0003_auto_20200718_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='offer', to='advertise.Offer'),
            preserve_default=False,
        ),
    ]
