# Generated by Django 3.0.5 on 2020-12-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='not_seen',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
