# Generated by Django 3.0.5 on 2020-11-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_massage_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='not_seen',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
