# Generated by Django 3.0.5 on 2020-08-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_massage_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
