# Generated by Django 3.0.5 on 2020-08-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation_last_massage_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_massage_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
