# Generated by Django 3.0.5 on 2020-08-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200822_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='last_massage_time',
        ),
    ]
