# Generated by Django 3.0.5 on 2020-08-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_conversation_last_massage_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='new_massage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
