# Generated by Django 3.0.5 on 2020-09-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20200921_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
