# Generated by Django 3.0.5 on 2020-11-14 17:01

import core.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('category', models.IntegerField(choices=[(0, 'مدارک و مستندات'), (1, 'کتاب و مجله'), (2, 'لوازم الکترونیکی'), (3, 'کفش و پوشاک'), (4, 'لوازم آرایشی و بهداشتی'), (5, 'دارو'), (6, 'سایر موارد')])),
                ('category_other', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MaxValueValidator(30.0), django.core.validators.MinValueValidator(0.0)])),
                ('dimension', models.IntegerField(choices=[(0, 'کوچک'), (1, 'متوسط'), (2, 'بزرگ')])),
                ('suggested_price', models.PositiveIntegerField(default=0)),
                ('buy', models.BooleanField(default=False)),
                ('phonenumber_visible', models.BooleanField(default=False)),
                ('picture', models.IntegerField(default=1)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('offer_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(db_index=True, default=core.utils.generate_slug, editable=False, max_length=8, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'منتشر شده'), (1, 'دارای پیشنهاد'), (2, 'در انتظار پرداخت'), (3, 'در انتظار خرید'), (4, 'در انتظار تحویل'), (5, 'در انتظار تایید خریدار'), (6, 'انجام شده'), (7, 'تمام شده'), (8, 'حذف شده'), (9, 'منقضی شده'), (10, 'در انتظار تایید'), (11, 'عدم تایید')], default=10)),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_city', to='account.City')),
                ('destination_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_country', to='account.Country')),
                ('origin_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_city', to='account.City')),
                ('origin_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_country', to='account.Country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight_date_start', models.DateField()),
                ('flight_date_end', models.DateField(blank=True, null=True)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('offer_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('income', models.PositiveIntegerField(default=0)),
                ('approved_packet', models.PositiveIntegerField(default=0)),
                ('slug', models.CharField(db_index=True, default=core.utils.generate_slug, editable=False, max_length=8, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'در انتظار تایید'), (1, 'عدم تایید'), (2, 'منتشر شده'), (3, 'دارای بسته'), (4, 'انجام شده'), (5, 'حذف شده'), (6, 'تسویه شده'), (7, 'تسویه نشده'), (8, 'در انتظار تسویه')], default=0)),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depar_country', to='account.Country')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depar_city', to='account.City')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dest_country', to='account.Country')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dest_city', to='account.City')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=15)),
                ('text', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertise.Packet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PacketPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_file', models.FileField(upload_to='images/%Y/%m')),
                ('packet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertise.Packet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(default=core.utils.generate_slug, editable=False, max_length=8, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'در انتظار پاسخ'), (1, 'در انتظار تایید مسافر'), (2, 'در انتظار پرداخت'), (3, 'در انتظار خرید'), (4, 'در انتظار تحویل'), (5, 'در انتظار تایید خریدار'), (6, 'انجام شده'), (7, 'تمام شده'), (8, 'حذف شده')], default=0)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packet_ads', to='advertise.Packet')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_ads', to='advertise.Travel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Buyinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packet_info', to='advertise.Packet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookmark_owner', to=settings.AUTH_USER_MODEL)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_packet', to='advertise.Packet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
