# Generated by Django 3.0.5 on 2020-07-14 08:40

import advertise.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('category', models.IntegerField(choices=[(0, 'مدارک و مستندات'), (1, 'کتاب و مجله'), (2, 'لوازم الکترونیکی'), (3, 'کفش و پوشاک'), (4, 'لوازم آرایشی و بهداشتی'), (5, 'سایر موارد')])),
                ('weight', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)])),
                ('suggested_price', models.PositiveIntegerField()),
                ('buy', models.BooleanField(default=False)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('offer_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(db_index=True, default=advertise.utils.generate_slug, editable=False, max_length=8, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'در انتظار تایید'), (1, 'عدم تایید'), (2, 'منتشر شده'), (3, 'دارای پیشنهاد'), (4, 'منقضی شده'), (5, 'حذف شده'), (6, 'در انتظار پرداخت'), (7, 'در انتظار خرید'), (8, 'خریداری شده'), (9, 'در حال ارسال'), (10, 'انجام شده')], default=0)),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_city', to='account.City')),
                ('destination_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_country', to='account.Country')),
                ('origin_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_city', to='account.City')),
                ('origin_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_country', to='account.Country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empty_weight', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)])),
                ('flight_date_start', models.CharField(max_length=40)),
                ('flight_date_end', models.CharField(max_length=40)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('offer_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('slug', models.CharField(db_index=True, default=advertise.utils.generate_slug, editable=False, max_length=8, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'در انتظار تایید'), (1, 'عدم تایید'), (2, 'منتشر شده'), (3, 'دارای بسته'), (4, 'انجام شده'), (5, 'حذف شده')], default=0)),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depar_country', to='account.Country')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depar_city', to='account.City')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dest_country', to='account.Country')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dest_city', to='account.City')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=15)),
                ('text', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='account.Profile')),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertise.Packet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PacketPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_file', models.FileField(upload_to='images/%Y/%m')),
                ('packet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertise.Packet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='packet',
            name='picture',
            field=models.ManyToManyField(blank=True, related_name='packets', to='advertise.PacketPicture'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('slug', models.CharField(default=advertise.utils.generate_slug, editable=False, max_length=8, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'در انتظار پاسخ'), (1, 'تایید'), (2, 'عدم تایید')], default=0)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packet_ads', to='advertise.Packet')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_ads', to='advertise.Travel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='advertise.Packet')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookmark_owner', to='account.Profile')),
                ('travel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertise.Travel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
