# Generated by Django 3.0.5 on 2020-11-19 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='origin_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='origin_city', to='account.City'),
        ),
        migrations.AlterField(
            model_name='packet',
            name='origin_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='origin_country', to='account.Country'),
        ),
    ]
