# Generated by Django 3.0.5 on 2020-06-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('0', 'در انتظار پاسخ'), ('1', 'تایید '), ('2', 'عدم تایید'), ('3', 'در انتظار پرداخت'), ('4', 'پرداخت شده')], default='0', max_length=3),
        ),
    ]
