# Generated by Django 3.0.5 on 2020-07-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='flight_date',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='owner',
        ),
        migrations.AddField(
            model_name='offer',
            name='travel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='travel_ads', to='advertise.Travel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packet',
            name='status',
            field=models.IntegerField(choices=[(0, 'در انتظار تایید'), (1, 'عدم تایید'), (2, 'منتشر شده'), (3, 'دارای پیشنهاد'), (4, 'منقضی شده'), (5, 'حذف شده'), (6, 'در انتظار پرداخت'), (7, 'در انتظار خرید'), (8, 'خریداری شده'), (9, 'در حال ارسال'), (10, 'انجام شده')], default=0),
        ),
        migrations.AlterField(
            model_name='travel',
            name='status',
            field=models.IntegerField(choices=[(0, 'در انتظار تایید'), (1, 'عدم تایید'), (2, 'منتشر شده'), (3, 'دارای بسته'), (4, 'انجام شده'), (5, 'حذف شده')], default=0),
        ),
    ]
