# Generated by Django 3.0.5 on 2020-11-27 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('picture', models.ImageField(upload_to='images/category')),
                ('level', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='packet',
            name='status',
            field=models.IntegerField(choices=[(0, 'منتشر شده'), (1, 'دارای پیشنهاد'), (2, 'در انتظار پرداخت'), (3, 'در انتظار خرید'), (4, 'در انتظار تحویل'), (5, 'در انتظار تایید خریدار'), (6, 'انجام شده'), (7, 'تمام شده'), (8, 'حذف شده'), (9, 'منقضی شده'), (10, 'در انتظار تایید'), (11, 'عدم تایید')], default=10),
        ),
        migrations.AlterField(
            model_name='packet',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='advertise.Category'),
        ),
    ]
