# Generated by Django 3.0.5 on 2020-11-24 10:22

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='slug',
            field=models.CharField(default=core.utils.generate_slug, editable=False, max_length=8, unique=True),
        ),
    ]
