# Generated by Django 3.0.5 on 2020-07-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='flight_date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='travel',
            name='flight_date_start',
            field=models.DateField(),
        ),
    ]
