# Generated by Django 3.0.5 on 2020-11-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='dimension',
            field=models.IntegerField(choices=[(0, 'کوچک'), (1, 'متوسط'), (2, 'بزرگ')]),
        ),
    ]
