# Generated by Django 3.0.5 on 2020-07-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_auto_20200714_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='flight_date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
