# Generated by Django 3.0.5 on 2020-12-16 03:10

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_auto_20201211_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(choices=[(0, 'عدم تطابق آگهی با صحبت\u200cهای بیلیگر'), (1, 'مغایرت محتویات بسته با قوانین'), (2, 'دستمزد نامتعارف'), (3, 'به دلایل دیگر')], max_length=1),
        ),
        migrations.CreateModel(
            name='RemoveReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_remove', models.CharField(choices=[(0, 'بسته از طریق دیگری ارسال شد'), (1, 'پیشنهادی دریافت نکردم'), (2, 'منصرف شدم'), (3, 'به دلایل دیگر')], max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='advertise.Packet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
