# Generated by Django 3.0.5 on 2020-06-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_auto_20200628_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
