# Generated by Django 3.0.5 on 2020-11-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_auto_20201119_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='parcelPrice',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
