# Generated by Django 3.0.5 on 2020-06-15 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertise', '0002_auto_20200614_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packet',
            name='category',
            field=models.CharField(choices=[('مدارک', '0'), ('1', 'کتاب'), ('2', 'سایر موارد')], max_length=20),
        ),
    ]
