# Generated by Django 3.0.5 on 2020-08-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0003_auto_20200722_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.IntegerField(choices=[(0, 'در انتظار پاسخ'), (1, 'تایید'), (2, 'عدم تایید'), (3, 'در انتظار پرداخت'), (4, 'در انتظار خرید'), (5, 'خریداری شده'), (6, 'در حال ارسال'), (7, 'انجام شده'), (8, 'در حال مذاکره')], default=0),
        ),
    ]
