# Generated by Django 3.0.5 on 2020-12-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0003_auto_20201216_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='removereason',
            name='type_remove',
            field=models.IntegerField(choices=[(0, 'بسته از طریق دیگری ارسال شد'), (1, 'پیشنهادی دریافت نکردم'), (2, 'منصرف شدم'), (3, 'به دلایل دیگر')]),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.IntegerField(choices=[(0, 'عدم تطابق آگهی با صحبت\u200cهای بیلیگر'), (1, 'مغایرت محتویات بسته با قوانین'), (2, 'دستمزد نامتعارف'), (3, 'به دلایل دیگر')]),
        ),
    ]
