# Generated by Django 3.0.5 on 2020-06-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0003_auto_20200630_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
