# Generated by Django 3.0.5 on 2020-07-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0003_auto_20200711_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='flight_date_end',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
