# Generated by Django 3.0.5 on 2020-06-17 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0004_offer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='packet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packet_ads', to='advertise.Packet'),
        ),
    ]
