# Generated by Django 3.0.5 on 2020-06-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0004_auto_20200607_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_file', models.FileField(upload_to='images/%Y/%m')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
