# Generated by Django 3.0.5 on 2020-06-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0004_auto_20200630_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
