# Generated by Django 3.0.5 on 2020-11-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0004_auto_20201121_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='parcelPrice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
