# Generated by Django 3.0.5 on 2020-12-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0005_offer_offer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.IntegerField(choices=[(0, 'مسافر'), (1, 'خرید'), (2, 'اشتراک')], default=0),
        ),
    ]
