# Generated by Django 3.0.5 on 2020-11-21 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201121_1323'),
        ('advertise', '0005_auto_20201121_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='no_matter_origin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='packet',
            name='origin_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_city', to='account.City'),
        ),
        migrations.AlterField(
            model_name='packet',
            name='origin_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_country', to='account.Country'),
        ),
    ]
