# Generated by Django 3.0.5 on 2020-06-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0005_auto_20200630_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packet',
            name='picture',
        ),
        migrations.AddField(
            model_name='packet',
            name='picture',
            field=models.ManyToManyField(blank=True, null=True, related_name='packets', to='advertise.PacketPicture'),
        ),
    ]
