# Generated by Django 3.0.5 on 2020-06-09 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0005_packetpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetpicture',
            name='packet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertise.Packet'),
        ),
    ]
