# Generated by Django 3.0.5 on 2020-06-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0006_auto_20200630_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='picture',
            field=models.ManyToManyField(blank=True, related_name='packets', to='advertise.PacketPicture'),
        ),
    ]
