# Generated by Django 3.0.5 on 2020-12-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0006_auto_20201220_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='eng_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
