# Generated by Django 3.0.5 on 2020-08-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0007_auto_20200819_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='approved_paccket',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='travel',
            name='income',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
