# Generated by Django 3.0.5 on 2020-07-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0007_auto_20200630_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='flight_date',
            new_name='flight_date_start',
        ),
        migrations.AddField(
            model_name='travel',
            name='flight_date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
