# Generated by Django 3.0.5 on 2020-08-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0008_auto_20200828_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='approved_paccket',
            new_name='approved_packet',
        ),
    ]
