# Generated by Django 3.0.5 on 2020-09-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0009_auto_20200828_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.IntegerField(choices=[(0, 'در انتظار پاسخ'), (1, 'تایید'), (2, 'عدم تایید'), (3, 'نهایی\u200cکردن مبلغ'), (4, 'تایید مبلغ'), (5, 'حذف شده')], default=0),
        ),
        migrations.AlterField(
            model_name='packet',
            name='status',
            field=models.IntegerField(choices=[(0, 'در انتظار تایید'), (1, 'عدم تایید'), (2, 'منتشر شده'), (3, 'دارای پیشنهاد'), (4, 'منقضی شده'), (5, 'حذف شده'), (6, 'در انتظار پرداخت'), (7, 'در حال انجام'), (8, 'در حال ارسال'), (9, 'انجام شده')], default=0),
        ),
    ]
