# Generated by Django 3.0.5 on 2020-12-28 22:37

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0010_auto_20201229_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='slug',
            field=models.CharField(default=core.utils.generate_slug, editable=False, max_length=10, unique=True),
        ),
    ]
