# Generated by Django 3.0.5 on 2020-09-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0011_auto_20200906_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.IntegerField(choices=[(0, 'در انتظار پاسخ'), (1, 'در انتظار تایید مسافر'), (2, 'در انتظار پرداخت'), (3, 'در انتظار خرید'), (4, 'در انتظار تحویل'), (5, 'در انتظار تایید خریدار'), (6, 'انجام شده'), (7, 'حذف شده')], default=0),
        ),
    ]
