# Generated by Django 3.0.5 on 2020-12-31 00:04

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0011_auto_20201229_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRemoveReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_remove', models.IntegerField(choices=[(0, 'آگهی مناسبی پیدا نکردم'), (1, 'سفرم کنسل شد'), (2, 'از قبول آگهی منصرف شدم'), (3, 'به دلایل دیگر')])),
                ('description', models.TextField(blank=True, null=True)),
                ('travel', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='advertise.Travel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
