# Generated by Django 3.0.5 on 2021-01-02 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0012_travelremovereason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packet',
            name='category_other',
        ),
        migrations.AlterField(
            model_name='travelremovereason',
            name='type_remove',
            field=models.IntegerField(choices=[(0, 'آگهی مناسبی پیدا نکردم'), (1, 'سفرم کنسل شد'), (2, 'هیچ کدوم از پیشنهاداتم قبول نشد'), (3, 'دستمزدها کم بود'), (4, 'به دلایل دیگر')]),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('eng_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_categoty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertise.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='packet',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='advertise.SubCategory'),
            preserve_default=False,
        ),
    ]
