# Generated by Django 3.0.5 on 2021-01-02 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0013_auto_20210102_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='advertise.SubCategory'),
        ),
    ]
