# Generated by Django 3.0.5 on 2021-01-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0014_auto_20210102_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.FileField(upload_to='images/category'),
        ),
    ]
