# Generated by Django 3.0.5 on 2020-09-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0014_auto_20200910_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='picture',
            field=models.ManyToManyField(blank=True, related_name='packets', to='advertise.PacketPicture'),
        ),
        migrations.AlterField(
            model_name='packetpicture',
            name='image_file',
            field=models.ImageField(upload_to='images/test/%Y/%m'),
        ),
    ]
