# Generated by Django 3.0.5 on 2021-01-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0015_auto_20210102_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='parent_categoty',
            new_name='categoty',
        ),
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
    ]
