# Generated by Django 3.0.5 on 2020-09-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0015_auto_20200910_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packetpicture',
            name='image_file',
            field=models.FileField(upload_to='images/%Y/%m'),
        ),
    ]
