# Generated by Django 3.0.5 on 2020-09-13 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0016_auto_20200910_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='dimension',
            field=models.IntegerField(choices=[(0, 'حیلی کوچک'), (1, 'کوچک'), (2, 'متوسط'), (3, 'بزرگ'), (4, 'خیلی بزرگ')]),
        ),
        migrations.CreateModel(
            name='Buyinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                # ('Packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packet_info', to='advertise.Packet')),
            ],
            options={
                'abstract': False,
            },
        ),
        # migrations.AddField(
        #     model_name='packet',
        #     name='buyinfo',
        #     field=models.ForeignKey(default =  , on_delete=django.db.models.deletion.PROTECT, to='advertise.Buyinfo'),
        #     preserve_default=False,
        # ),
    ]
