# Generated by Django 3.0.5 on 2020-09-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0017_auto_20200913_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyinfo',
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
