# Generated by Django 3.0.5 on 2021-01-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0017_buyinfo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyinfo',
            name='slug',
        ),
    ]
