# Generated by Django 3.0.5 on 2020-09-13 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0018_auto_20200913_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packet_info', to='advertise.Packet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
