# Generated by Django 3.0.5 on 2020-09-13 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0025_auto_20200913_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MaxValueValidator(30.0), django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
