# Generated by Django 3.0.5 on 2020-09-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0026_auto_20200913_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
