# Generated by Django 3.0.5 on 2020-09-13 08:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0034_auto_20200913_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='empty_weight',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='advertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertise.Packet'),
        ),
        migrations.AlterField(
            model_name='packet',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MaxValueValidator(30.0), django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
