# Generated by Django 3.0.5 on 2020-09-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0035_auto_20200913_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='category_other',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
