# Generated by Django 3.0.5 on 2020-09-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0036_packet_category_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='category_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
