# Generated by Django 3.0.5 on 2020-09-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0038_auto_20200913_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='category_other',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
