# Generated by Django 3.0.5 on 2020-09-16 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0039_auto_20200916_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packet',
            name='picture',
        ),
        migrations.AddField(
            model_name='packet',
            name='picture',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packet',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MaxValueValidator(30.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
