# Generated by Django 3.0.5 on 2020-09-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0042_auto_20200921_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyinfo',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='packet',
            name='suggested_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
