# Generated by Django 3.0.5 on 2020-10-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0043_auto_20200921_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='picture',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
